parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'next/core-web-vitals'
  - 'prettier'
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'unused-imports'
rules:
  '@typescript-eslint/no-unused-vars': warn
  unused-imports/no-unused-imports: warn
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      pathGroups:
        - pattern: '@app/**'
          group: 'internal'
          position: 'before'
      alphabetize:
        order: asc
        caseInsensitive: true
